name: "Mindctrl"
description: "LLMOps for Homeassistant"
version: "0.0.43"
url: "https://github.com/akshaya-a/mindctrl/tree/main/mindctrl-addon"
slug: "mindctrl"
init: false
arch:
  - aarch64
  - amd64
startup: services
homeassistant_api: true
hassio_api: true # Discover gateway
hassio_role: manager
panel_icon: mdi:flask
panel_title: Mindctrl
ingress: true
ingress_port: 5002
ports:
  5000/tcp: 5000 # tracking server
  5002/tcp: 5002 # multiserver
  9999/tcp: 9999 # dashboard
ports_description:
  5000/tcp: "MLflow Server"
  5002/tcp: "Mindctrl Server"
  9999/tcp: "Dashboard"
discovery:
  - mindctrl
map:
  - share:rw # Used for artifacts storage, expects "tracking" share in HA.
environment:
  FORWARDED_ALLOW_IPS: "172.30.32.2" # Supervisor: https://developers.home-assistant.io/docs/add-ons/presentation#ingress
image: "ghcr.io/akshaya-a/{arch}-mindctrl"
options:
  OPENAI_API_KEY: ""
  MQTT_BROKER: "localhost"
  MQTT_PORT: "1883"
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_ADDRESS: ""
  POSTGRES_PORT: ""
  server_pip_packages: # TODO: not working for debugging, figure out later
    - mlflow==2.7.1
    - azureml-mlflow
    - fastapi
    - uvicorn[standard]
    - openai
    - homeassistant
schema:
  OPENAI_API_KEY: str
  MQTT_BROKER: str
  MQTT_PORT: int
  MQTT_USERNAME: str
  MQTT_PASSWORD: str
  POSTGRES_USER: str
  POSTGRES_PASSWORD: str
  POSTGRES_ADDRESS: str
  POSTGRES_PORT: int
  server_pip_packages:
    - "match(.*)" # TODO: figure out a better regex for version specifiers
