name: "Mindctrl"
description: "LLMOps for Homeassistant"
version: "0.0.47"
url: "https://github.com/akshaya-a/mindctrl/tree/main/mindctrl-addon"
slug: "mindctrl"
init: false
arch:
  - aarch64
  - amd64
startup: services
homeassistant_api: true
hassio_api: true # Discover gateway
hassio_role: manager
panel_icon: mdi:flask
panel_title: Mindctrl
ingress: true
ingress_port: 5002
ports:
  5000/tcp: 5000 # tracking server
  5002/tcp: 5002 # multiserver
  9999/tcp: 9999 # dashboard
ports_description:
  5000/tcp: "MLflow Server"
  5002/tcp: "Mindctrl Server"
  9999/tcp: "Dashboard"
discovery:
  - mindctrl
map:
  - share:rw # Used for artifacts storage, expects "tracking" share in HA.
  - addon_config:rw # Used for replay server inputs and outputs
environment:
  FORWARDED_ALLOW_IPS: "172.30.32.2" # Supervisor: https://developers.home-assistant.io/docs/add-ons/presentation#ingress
image: "ghcr.io/akshaya-a/{arch}-mindctrl"
options:
  STORE__STORE_TYPE: "psql"
  STORE__USER: "mindctrl"
  STORE__PASSWORD: ""
  STORE__ADDRESS: "localhost"
  STORE__PORT: "5432"
  STORE__DATABASE: "mindctrl"
  EVENTS__EVENTS_TYPE: "mqtt"
  EVENTS__BROKER: "localhost"
  EVENTS__PORT: "1883"
  EVENTS__USERNAME: "mindctrl"
  EVENTS__PASSWORD: ""
  OPENAI_API_KEY: ""
schema:
  STORE__STORE_TYPE: str
  STORE__USER: str
  STORE__PASSWORD: str
  STORE__ADDRESS: str
  STORE__PORT: str
  STORE__DATABASE: str
  EVENTS__EVENTS_TYPE: str
  EVENTS__BROKER: str
  EVENTS__PORT: str
  EVENTS__USERNAME: str
  EVENTS__PASSWORD: str
  OPENAI_API_KEY: str
