# Traefik dynamic configuration file
# See https://doc.traefik.io/traefik/getting-started/configuration-overview/#the-dynamic-configuration

# TODO: How to unify with k8s Ingress?
http:
  routers:
    # https://github.com/mlflow/mlflow/issues/4484#issuecomment-919377871
    to-mindctrl:
      rule: "PathPrefix(`/mindctrl`)"
      service: mindctrl
      priority: 5
      middlewares:
        - "addon-ipallowlist"
      entryPoints:
        - http
    # TODO: Mlflow API can't be prefixed and traefik rewrites are hard
    mlflow-api:
      rule: "PathPrefix(`/api`)"
      service: tracking
      priority: 4
      middlewares:
        - "addon-ipallowlist"
      entryPoints:
        - http
    mlflow-ui:
      rule: "PathPrefix(`/mlflow`)"
      service: tracking
      priority: 3
      middlewares:
        - "addon-ipallowlist"
        - "add-addon-ingress"
      entryPoints:
        - http
    dapr-dashboard:
      rule: "PathPrefix(`/dapr-dashboard`)"
      service: daprdashboard
      priority: 2
      middlewares:
        - "addon-ipallowlist"
        - "add-addon-ingress"
      entryPoints:
        - http
    root-ingress:
      rule: "PathPrefix(`/`)"
      service: mindctrl
      priority: 1
      middlewares:
        - "addon-ipallowlist"
      entryPoints:
        - http

  middlewares:
    add-addon-ingress:
      addPrefix:
        prefix: "{{ env "HASS_INGRESS_ENTRY" }}"
    addon-ipallowlist:
      ipAllowList:
        sourceRange:
          - "{{ env "TRAEFIK_ALLOW_IP" }}"
          {{- if (env "TRAEFIK_ALLOW_IPV6") }}
          - "{{ env "TRAEFIK_ALLOW_IPV6" }}"
          {{- end }}

  services:
    mindctrl:
      loadBalancer:
        servers:
          - url: "{{ env "MINDCTRL_SERVER_URI" }}"
    tracking:
      loadBalancer:
        servers:
          - url: "{{ env "MLFLOW_TRACKING_URI" }}"
    daprdashboard:
      loadBalancer:
        servers:
          - url: "{{ env "DAPR_DASHBOARD_URI" }}"
