# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
# TODO: migrate to HA base images - they don't have ubuntu+python so deal with it later
build_from:
  aarch64: "ghcr.io/hassio-addons/debian-base:7.2.0"
  amd64: "ghcr.io/hassio-addons/debian-base:7.2.0"
labels:
  org.opencontainers.image.title: "MLflow Gateway for Home Assistant"
  org.opencontainers.image.description: "MLflow Gateway for managing model providers"
  org.opencontainers.image.source: "https://github.com/akshaya-a/mlflow-hass/tree/main/mlflow-gateway"
  org.opencontainers.image.licenses: "Apache License 2.0"
