endpoints:
  - name: completions
    endpoint_type: llm/v1/completions
    model:
      provider: openai
      name: gpt-3.5-turbo
      config:
        openai_api_key: $OPENAI_API_KEY

  - name: chat35t
    endpoint_type: llm/v1/chat
    model:
      provider: openai
      name: gpt-3.5-turbo
      config:
        openai_api_key: $OPENAI_API_KEY

  - name: chat4t
    endpoint_type: llm/v1/chat
    model:
      provider: openai
      name: gpt-4-turbo-preview
      config:
        openai_api_key: $OPENAI_API_KEY

  - name: chat4o
    endpoint_type: llm/v1/chat
    model:
      provider: openai
      name: gpt-4o
      config:
        openai_api_key: $OPENAI_API_KEY

  - name: embeddings
    endpoint_type: llm/v1/embeddings
    model:
      provider: openai
      name: text-embedding-ada-002
      config:
        openai_api_key: $OPENAI_API_KEY
