# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/mlflow/mlflow:v2.7.1"
  amd64: "ghcr.io/mlflow/mlflow:v2.7.1"
labels:
  org.opencontainers.image.title: "MLflow Tracking Server for Home Assistant"
  org.opencontainers.image.description: "MLflow Tracking Server for managing models + prompts"
  org.opencontainers.image.source: "https://github.com/akshaya-a/mlflow-hass/tree/main/mlflow-tracking"
  org.opencontainers.image.licenses: "Apache License 2.0"
