name: "mlflow-tracking"
description: "MLflow Tracking Server for managing models + prompts"
version: "0.0.2"
url: "https://github.com/akshaya-a/mlflow-hass/tree/main/mlflow-tracking"
slug: "mlflow-tracking"
init: false
arch:
  - aarch64
  - amd64
startup: services
homeassistant_api: true
ingress: true
panel_icon: mdi:console
panel_title: MLflow
ports:
  8099/tcp: 8099
