# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/debian-base:7.3.3"
  amd64: "ghcr.io/hassio-addons/debian-base:7.3.3"
labels:
  org.opencontainers.image.title: "LLMOps for Home Assistant"
  org.opencontainers.image.description: "MLflow Store+Gateway+Model Server"
  org.opencontainers.image.source: "https://github.com/akshaya-a/mindctrl/tree/main/addons/mindctrl"
  org.opencontainers.image.licenses: "Apache License 2.0"
