# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Addon Integration Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Addon Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          uv pip install --system -r tests/test-requirements.txt python/
      - name: Lint with Ruff
        run: |
          ruff check .
      - name: install playwright deps
        run: |
          playwright install --with-deps chromium
      - name: Copy python source + services into build context because builder action doesn't support --build-context
        id: copy
        run: bash scripts/copy_content_to_addon_context.sh
      - name: Test with pytest
        run: |
          pytest -v -s -rA -c tests/pytest.ini --deploy-mode=addon --replay-mode=replay
