# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: K3D Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mindctrl-addon/test-requirements.txt python/
      - name: Lint with Ruff
        run: |
          ruff check .
      - name: Create cluster
        shell: bash
        run: bash scripts/setup_k3d.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_CREATION: true
          SKIP_REGISTRY_CREATION: true
          SKIP_READINESS: true
      - name: Install Dapr
        shell: bash
        run: |
          wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
      - name: Test with pytest
        run: |
          pytest -v -s -c tests/pytest.ini --deploy-mode=k3d --replay-mode=replay
