# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Integration Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deploymode: ["local", "k3d", "addon"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          uv pip install --system -r tests/test-requirements.txt python/
      - name: Lint with Ruff
        run: |
          ruff check .
      - name: Create cluster
        if: startsWith(matrix.deploymode, 'k3') == true
        shell: bash
        run: bash scripts/setup_k3d.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_CREATION: true
          SKIP_REGISTRY_CREATION: true
          SKIP_READINESS: true
      - name: install playwright deps
        run: |
          playwright install --with-deps chromium
      - name: Copy content to addon context
        if: startsWith(matrix.deploymode, 'addon') == true
        id: copy
        run: bash scripts/copy_content_to_addon_context.sh
      - name: Install Dapr
        shell: bash
        run: |
          wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
      - name: initialize dapr
        run: |
          dapr init --slim
      - name: Test with pytest
        run: |
          pytest -v -s -rA -c tests/pytest.ini --deploy-mode=${{ matrix.deploymode }} --replay-mode=replay
      - name: Upload debug playwright screenshots
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots-${{ matrix.deploymode }}
          path: "**/fail-*.png"
