name: k3s

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: nolar/setup-k3d-k3s@v1
        name: Create cluster
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check k3s
        run: kubectl get nodes
      - name: Dapr tool installer
        uses: dapr/setup-dapr@v1
      - name: Initialize Dapr
        shell: bash
        run: |
          # Initialize Dapr
          # Group the Dapr init logs so these lines can be collapsed.
          echo "::group::Initialize Dapr"
          dapr init --kubernetes --wait
          echo "::endgroup::"

          dapr status --kubernetes
        working-directory: ./mindctrl-addon/rootfs/usr/bin
      - name: Deploy mindctrl
        shell: bash
        run: |
          ls -a
          dapr run -k -f dapr-k8s.yaml
        working-directory: ./mindctrl-addon/rootfs/usr/bin
