name: k3s

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: nolar/setup-k3d-k3s@v1
        name: Create cluster
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check k3s
        run: kubectl get nodes
      - name: Install Dapr
        shell: bash
        run: |
          wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
      - name: Initialize Dapr
        shell: bash
        run: |
          # Initialize Dapr
          # Group the Dapr init logs so these lines can be collapsed.
          echo "::group::Initialize Dapr"
          dapr init --kubernetes --wait
          echo "::endgroup::"

          dapr status --kubernetes
        working-directory: ./mindctrl-addon/rootfs/usr/bin
      - name: Deploy mindctrl
        shell: bash
        run: |
          dapr run -k -f dapr-k8s.yaml &
          echo "sleeping"
          sleep 60
          kubectl get pods
          sleep 60
          kubectl get pods
          sleep 60
          echo "logs below"
          # docker exec k3d-k3s-default-server-0 sh -c "cd /var/log/pods && ls -a && cat * */*"
          docker exec k3d-k3s-default-server-0 sh -c "find /var/log/pods -type f -name "*.log" | grep -i multiserver | xargs cat"
        working-directory: ./mindctrl-addon/rootfs/usr/bin
