kind: Service
apiVersion: v1
metadata:
  name: deployments-service
  labels:
    app: deployments
spec:
  selector:
    app: deployments
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployments
  labels:
    app: deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployments
  template:
    metadata:
      labels:
        app: deployments
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "deployments"
        dapr.io/app-port: "5001"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: deployments
          image: $REGISTRY_NAME:$REGISTRY_PORT/deployments:latest
          # command: ["/bin/bash", "-c", "--"]
          # args: ["while true; do sleep 30; done;"]
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: openai-api-key
            - name: APP_PORT
              value: "5001"
          ports:
            - containerPort: 5001
          imagePullPolicy: Always
