kind: Service
apiVersion: v1
metadata:
  name: mosquitto-service
  labels:
    app: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "mosquitto"
        dapr.io/app-port: "1883"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          command: ["mosquitto", "-c", "/mosquitto-no-auth.conf"]
          # args: ["mosquitto -c /mosquitto-no-auth.conf"]
          env:
            - name: APP_PORT
              value: "1883"
          ports:
            - containerPort: 1883
          imagePullPolicy: Always
