kind: Service
apiVersion: v1
metadata:
  name: tracking-service
  labels:
    app: tracking
spec:
  selector:
    app: tracking
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking
  labels:
    app: tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking
  template:
    metadata:
      labels:
        app: tracking
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "tracking"
        dapr.io/app-port: "5000"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: tracking
          image: $K3D_REGISTRY_URL/tracking:latest
          # command: ["/bin/bash", "-c", "--"]
          # args: ["while true; do sleep 30; done;"]
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: openai-api-key
            - name: APP_PORT
              value: "5000"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
